name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy: # اسم الـ job
    runs-on: ubuntu-latest

    steps:
    # الخطوة 1: جيب الكود (زي ما هي)
    - uses: actions/checkout@v3

    # الخطوة 2: الـ Deploy علطول (شلنا كل خطوات الـ build)
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        projectId: "orpita-studio"
        target: "orpita-studio"
        channelId: live